sonar.projectKey=ChipanaFadiley_ucv-ate-si-lab09
sonar.organization=chipanaadiley
sonar.sources=travel_assistant
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.host.url=https://sonarcloud.io